var ua="function"==typeof Object.defineProperties?Object.defineProperty:function(m,K,ha){m!=Array.prototype&&m!=Object.prototype&&(m[K]=ha.value)},ab="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function Bb(){Bb=function(){};ab.Symbol||(ab.Symbol=Cb)}var Cb=function(){var m=0;return function(K){return"jscomp_symbol_"+(K||"")+m++}}();
function Db(){Bb();var m=ab.Symbol.iterator;m||(m=ab.Symbol.iterator=ab.Symbol("iterator"));"function"!=typeof Array.prototype[m]&&ua(Array.prototype,m,{configurable:!0,writable:!0,value:function(){return bc(this)}});Db=function(){}}function bc(m){var K=0;return cc(function(){return K<m.length?{done:!1,value:m[K++]}:{done:!0}})}function cc(m){Db();m={next:m};m[ab.Symbol.iterator]=function(){return this};return m}
function dc(m){if(!(m instanceof Array)){Db();var K=m[Symbol.iterator];m=K?K.call(m):bc(m);for(var ha=[];!(K=m.next()).done;)ha.push(K.value);m=ha}return m}
(function(m){function K(a){a.ownerDocument&&(a=ha(a));try{return a.frameElement}catch(b){return null}}function ha(a){a=a.ownerDocument;return a.defaultView||a.parentWindow}function Eb(a){var b=a.document;b=b.documentElement||b.body.parentNode||b.body;var c=a.pageXOffset!==m;return{x:D(c?a.pageXOffset:b.scrollLeft),y:D(c?a.pageYOffset:b.scrollTop)}}function Fb(a,b){function c(a,b,d){var f=d[a];if(b(f,d))return f;d=d.frames;for(f=d.length;0<f--;)try{var l=c(a,b,d[f]);if(l)return l}catch(wc){}}var d=
h,f=c(a,b,d);if(f)return f;do try{var v=d[a];if(b(v,d))return v}catch(l){}while(d!=X&&(d=d.parent));return null}function D(a){return parseInt(a,10)}function Pa(a){var b=b||901;return a.split("[ADL_SID]").join(Y).split("[ADL_VW]").join(V.C&&V.C.vwb[0]?1:0).split("[ADL_ATF]").join(V.C&&V.C.atf[0]?1:0).split("[ADL_FW]").join(~~S).split("[ERRORCODE]").join(b).split(/(?:\[|$\{|%%)CACHEBUST[A-Z]*(?:\]|\}|%%)/i).join(Math.floor(99E6*Math.random()+1E6)).split(/\[TIMESTAMP\]/i).join(O((new Date).toISOString()))}
function Gb(a){var b=b||null;var c={};if(a.currentStyle)for(b=a.currentStyle,a=b.length;0<a--;)c[b[a]]=b[b[a]];else for(b=ha(a).getComputedStyle(a,b),a=b.length;0<a--;)c[b[a]]=b.getPropertyValue(b[a]);delete c.cssText;return c}function va(a){a=a.getBoundingClientRect();a={left:D(a.left),right:D(a.right),top:D(a.top),bottom:D(a.bottom)};a.width=a.right-a.left;a.height=a.bottom-a.top;return a}function Hb(a,b){b?b.parentNode.insertBefore(a,b.nextSibling):(bb||w.body).appendChild(a)}function ec(a,b){var c=
"https://data00.adlooxtracking.com/ads/ic5.php?";a&&(c+=wa(a));var d=w.createElement("script");d.src=c;d.setAttribute("data-adloox-sid",Y);b&&(d.onload=x(b,"load"),d.onerror=x(b,"error"));Hb(d,L)}function xa(a){"function"==typeof a&&(a=a());"string"==typeof a&&Ha(Pa(a))}function cb(a){var b="https://data00.adlooxtracking.com/ads/ic5.php?";a&&(b+=wa(a));if("function"!=typeof C.sendBeacon||!C.sendBeacon(b,""))if(Z)try{var c=new XMLHttpRequest;c.open("GET",b,!1);c.send()}catch(B){Ha(b)}else Ha(b)}function Ha(a,
b){a&&(b&&(a+=wa(b)),(new Image).src=a)}function H(a,b){if(b)a[b]=H(a[b]);else return a[a.length-1]}function Qa(a){var b={};if(!a.length)return b;a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=",2),f=decodeURIComponent(d[0]);d=d[1];try{d=decodeURIComponent(d)}catch(v){}b[f]===m?b[f]=[d]:b[f].push(d)}return b}function wa(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&a[c]!==m&&b.push(O(c)+"="+O(a[c]));return b.join("&")}function O(a){return encodeURIComponent(a).replace(/[!'()*]/g,function(a){return"%"+
a.charCodeAt(0).toString(16)})}function Ib(a){var b=w.createElement("a");b.href=a;return b}function la(){Z||Ia&&db&&100>ca()-db||(Z=!0,y("unload"))}function eb(a,b){if(y.a[a])for(var c=y.a[a].length;0<c--;)y.a[a][c][0]==b&&y.a[a].splice(c,1)}function r(a,b){var c=c||this;y.a[a]?y.a[a].push([b,c]):y.a[a]=[[b,c]]}function y(a,b){b=b||{};if(Z)fb({name:a,detail:b});else if("function"==typeof h.CustomEvent)gb.dispatchEvent(new CustomEvent("e",{detail:{name:a,detail:b}}));else if("function"==typeof w.createEvent){var c=
w.createEvent("CustomEvent");c.initCustomEvent("e",!1,!0,{name:a,detail:b});gb.dispatchEvent(c)}else ma(x(fb,{name:a,detail:b}),0)}function fb(a){var b=y.a[a.name];if(b)for(var c=b.length;0<c--;)try{b[c][0].call(b[c][1],a.detail)}catch(B){ia("fire "+a.name+": "+(B.stack||B.message))}}function G(a,b,c){if(a.addEventListener)try{a.addEventListener(b,c,{passive:!0})}catch(B){a.addEventListener(b,c,!1)}else a.attachEvent("on"+b,c)}function x(a,b){var c=Array.prototype.slice.call(arguments,1);return Function.prototype.bind?
(c.unshift(null),Function.prototype.bind.apply(a,c)):function(){var b=Jb(arguments);return a.apply(this,c.concat(b))}}function Ja(a,b){return ma(a,b)}function Jb(a){for(var b=[],c=a.length;0<c--;)b.unshift(a[c]);return b}function ca(){return(new Date).getTime()}function W(){}var h=this,Kb=h.parent,X=h.top,aa=h.location,w=h.document,C=h.navigator,ya=h.screen,ba="appnexus_script",bb=w.head||w.getElementsByTagName("head")[0],L=function(){if(w.currentScript)return w.currentScript;for(var a=/\/(?:tmp_)?tfav_script1_appnexus\.js[#?]?/,
b=w.scripts,c=b.length;0<c--;)if(b[c]&&b[c].src&&b[c].src.match(a))return b[c];return null}(),Y=Math.floor(1E11*Math.random()+1);Object.keys||(Object.keys=function(a){var b=[],c;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b});var Ra=ca(),ma=h.setTimeout,gb=w.createElement("a"),Z=!1,db=0;G(h,"load",function(){db=ca()});y.a={};"function"!=typeof h.CustomEvent&&"function"!=typeof w.createEvent||gb.addEventListener("e",function(a){fb(a.detail)});r("impression",function(){h.setTimeout(function(){Z||
la()},57E4)});var fc=function(){return"undefined"!=typeof DOMParser?function(a){return(new h.DOMParser).parseFromString(a,"text/xml")}:"undefined"!=typeof ActiveXObject&&new h.ActiveXObject("Microsoft.XMLDOM")?function(a){var b=new h.ActiveXObject("Microsoft.XMLDOM");b.async="false";b.loadXML(a);return b}:W}();if(!L||bb&&bb.contains(L)||w.body&&w.body.contains(L)){var hb=[],Lb=!!h.opera,gc=!!h.InstallTrigger,hc=0<Object.prototype.toString.call(h.HTMLElement).indexOf("Constructor"),ic=!!h.chrome&&
!Lb,Sa=(new Function("return /*@cc_on!@*/!1"))()||!!w.documentMode,Ta=!1,za,E,g,Ia=/Version\/[0-9.]+ Chrome\/[0-9.]+ Mobile|iP(?:hone|od|ad).*AppleWebKit(?!.*Version\/[0-9.]+)|; wv/.test(C.userAgent),Mb=/Android|webOS|iP(?:hone|od|ad)|BlackBerry|mobi|Opera Mini/i.test(C.userAgent),jc=aa.protocol.match(/^https?:/)&&"null"===h.origin,Nb=Ia||Mb,ib=h!=X,Aa=h;try{for(;Aa!=X;)if(Aa.parent.document)Aa=Aa.parent;else break}catch(a){}var Ua=Aa==X,qa=function(a){function b(){var a=Array.prototype.slice,b=[w];
try{for(var c=h;c!=X&&"object"==typeof c.parent.document;)c=c.parent,b=b.concat([c.document])}catch(jb){}for(c=0;c<pa.length;c++){var d=pa[c];if(d)for(var l=0;l<b.length;l++){var v=[],k=b[l];try{var e=k.getElementById(d)}catch(jb){e=null}null!=e&&(v=v.concat([e]));try{e=k.getElementsByClassName(d)}catch(jb){e=null}v=v.concat(a.call(e));try{e=k.querySelector(d)}catch(jb){e=null}null!=e&&(v=v.concat([e]));for(k=0;k<v.length;k++)if(f(v[k]))return v[k];if(v.length)return v[0]}}return null}function c(a){function b(a){var b=
Math.log(qa.a-k+2);b*=b;if(!c)return b;var d=v(f);a=v(a);!d&&a?b*=.2:d&&!a&&(b*=5);return b}var c=null,f=null,e=null,k=qa.a,h=a;if(a.ownerDocument.getElementsByTagName("head")[0].contains(a)){a=a.ownerDocument.body.lastChild;do a=a.previousSibling;while(a&&1!=a.nodeType)}var B=null,t=null,N=null,F=null,g=0,n=0;do{if(!B&&!t&&a&&"BODY"!=a.tagName){B=t=N=F=a;(a=a.parentNode)&&"BODY"==a.tagName&&(a=null);do t=t.nextSibling;while(t&&1!=t.nodeType)}if(B&&g>=n){var u=l(B);var R=b(u);c&&u.width*u.height/
R<f.width*f.height/e||!d(B,u)||(c=B,e=R,f=u);N=B;do B=B.previousSibling;while(B&&1!=B.nodeType);for(;B&&B.children&&B.children.length;)B=B.children[B.children.length-1],g++}if(t&&n>=g){u=l(t);R=b(u);c&&u.width*u.height/R<f.width*f.height/e||!d(t,u)||(c=t,e=R,f=u);F=t;do t=t.nextSibling;while(t&&1!=t.nodeType);for(;t&&t.children&&t.children.length;)t=t.children[0],n++}!B&&N&&g>=n&&((B=N.parentNode)&&"BODY"==B.tagName&&(N=B=null),g--);!t&&F&&n>=g&&((t=F.parentNode)&&"BODY"==t.tagName&&(F=t=null),n--)}while((B||
t||a)&&0<k--);c||250!=qa.a||"complete"!==h.ownerDocument.readyState||(c=m);qa.a=Math.min(250,2*qa.a);return c}function d(a,b){switch(a.tagName){case "DIV":var c=a.style["background-image"];if(c&&!c.match(/^url\("?([^")]+)"?\)$/))break;case "SPAN":if(a.innerText&&a.innerText.trim())break;case "ARTICLE":case "VIDEO":case "IMG":case "CANVAS":case "OBJECT":case "EMBED":case "SVG":case "IFRAME":case "INS":return!("proxy"==a.getAttribute("data-adloox-type")||a.getAttribute("data-adloox-cname")==ba)&&f(a,
b)}return!1}function f(a,b){if(a.clientWidth+5<a.scrollWidth)return!1;b=b||va(a);return b.width<lb||b.height<mb?!1:0<=b.top+5&&0<=b.left+5}function v(a){return!!{"390x220":1,"320x240":1,"320x250":1,"320x300":1,"600x400":1,"330x280":1,"320x100":1,"970x250":1,"320x50":1,"120x20":1,"160x20":1,"210x30":1,"300x600":1,"300x1050":1,"970x90":1,"300x250":1,"180x150":1,"160x600":1,"720x90":1,"970x60":1,"120x60":1,"80x30":1,"600x250":1,"600x150":1,"600x600":1,"720x310":1,"550x480":1}[a.width+"x"+a.height]}function l(a){a=
va(a);a.width=10*(a.width/10|0);a.height=10*(a.height/10|0);return a}a||(a=w.body);try{if(pa.length)return b();var k=a;try{for(;!f(k)&&ha(k)!=X;){k=K(k);if(!k)break;a=k}}catch(t){}var e=K(a);k=null;k=c(a);!k&&e&&(k=c(e));if(!k){var g=a.ownerDocument.body;f(g)&&(k=g)}!k&&e&&(g=e.ownerDocument.body,f(g)&&(k=g));if(k){var r=l(k);do{var p=k.parentNode;if(!p||!d(p))break;var y=l(p);if(r.width!=y.width||r.height!=y.height)break;k=p}while(1)}return k}catch(t){ia(t.stack||t.message)}};qa.a=10;var Ob=h["tab_adloox_transaction_id_"+
ba]instanceof Array?h["tab_adloox_transaction_id_"+ba][0]:null,da=[],p={},Q=0,ja=0,M=0,ra=0,pa=[],Ba={},ea=0,Pb=0,Ca=1,Da=function(a){if(!(a>=(ra|ja)))for(a=Da.a.length;0<a--;)xa(Da.a[a])};Da.a=[];var Va=[];r("unload",function(){for(var a=Va.length;0<a--;)xa(Va[a])});if(L){var Qb=Ib(L.src),Wa=(Qb.hash||"").split("#").slice(1);Wa.length||(Wa=[(Qb.search||"").substr(1)]);if(Wa.length){p=Qa(Wa[0]);"id20"in p||(p.id20=["a661c72"]);for(var q in p)if(q.match(/^id[0-9]+$/))H(p,q),da[D(q.substr(2))-1]=p[q],
Ba[q]=p[q];else switch(q){case "platform":var nb=H(p[q]);break;case "fwtype":(ea=D(H(p[q])))&&(Ca=2==ea?"log":ea);!ea||3>ea?ea=1:3==ea&&(ea="wl");break;case "tagid":Pb=D(H(p[q]));break;case "creatype":var Ka=D(H(p[q]));break;case "targetelt":for(var z=p[q].length;0<z--;)p[q][z].length&&pa.unshift(p[q][z]);break;case "custom1area":var sa=D(H(p[q]));0<=sa&&100>=sa&&(Q=sa/100);break;case "custom2area":sa=D(H(p[q]));0<=sa&&100>=sa&&(M=sa/100);break;case "custom1sec":ja=parseFloat(H(p[q]))||ja;break;case "custom2sec":ra=
parseFloat(H(p[q]))||ra;break;case "px_imp":for(z=p[q].length;0<z--;)r("impression",x(xa,p[q][z]));break;case "px_view":for(z=p[q].length;0<z--;)r("visi",x(xa,p[q][z]));break;case "px_viewc":for(z=p[q].length;0<z--;)r("visi_custom",x(xa,p[q][z]));break;case "px_viewn":for(z=p[q].length;0<z--;)Da.a.push(p[q][z]);break;case "bridge":for(z=p[q].length;0<z--;)Va.push(p[q][z]);break;case "id":Y=H(p[q]);break;case "ping":Nb=!!D(H(p[q]));break;case "vast":var T=H(p[q])}"russia"===Ba.id12&&(Ca="log");for(var fa=
da.length;20>fa;fa++)da.push("")}L.setAttribute("data-adloox-sid",Y)}"issmedia_gpt"==ba&&(ra=M=1);var U=1==Ka,S=null,Xa=!("log"==Ca||4==Ca);U&&Xa&&(Xa=!1,Ca="log");var ob=Xa&&0<pa.length&&!T&&"adasia"==ba;"number"==typeof h.adloox_pc_viewed&&(M=h.adloox_pc_viewed);"number"==typeof h.adloox_time_viewed&&(ra=h.adloox_time_viewed);"string"==typeof h.adloox_target&&pa.push(h.adloox_target);var Rb="379",Sb="0",ta="",pb="",qb=w.title||"",lc=ya.width+"x"+ya.height,Tb="";try{Tb=C.hardwareConcurrency||""}catch(a){}var mc=
C.language||"",mb=20,lb=20,ia=function(a){ia.j[a]||(ia.j[a]=1,Ja(function(){delete ia.j[a]},5E3),(new Image).src="https://data00.adlooxtracking.com/ads/err.php?client="+O(ba)+"&js="+O("tfav_script1_appnexus")+"&visite_id="+O(Y)+"&err="+O(a))};ia.j={};try{var rb=!1;r("rect",function(){rb=!1});var Ya=function(){rb||Z||(rb=Ja(x(y,"geometry"),100))},d={},Ub=function(a){function b(){if(g)g.stopAd();else if(E)E.close();else if("BODY"!=a.tagName||a.A!=a.A.parent)a.style.visibility="hidden";la()}ob&&!1!==
S&&(a.style.visibility="hidden");d.o=a;d.A=ha(a);d.B=a.ownerDocument;a.setAttribute("data-adloox-type","el");a.setAttribute("data-adloox-sid",Y);a.setAttribute("data-adloox-cname",ba);if(T||g||6==Ka||23==Ka)2>ja&&(ja=2),.5>Q&&(Q=.5);else{var c=va(a);c=!Mb&&242500<=c.width*c.height?.3:.5;1>ja&&(ja=1);Q<c&&(Q=c)}T||!1===S?y("adunit"):!0===S?b():r("fw",function(c){c.state?b():(ob&&(a.style.visibility="visible"),y("adunit"))})};r("adunit",function(){G(d.A,"resize",Ya);G(d.A,"scroll",Ya);G(d.o,"mouseenter",
Ya);G(d.o,"mouseleave",Ya);y("geometry")});r("geometry",function(){var a=d.A,b=d.B,c=b.documentElement;d.N=Ia?ya.availWidth:a.innerWidth||c.clientWidth||b.body.clientWidth;d.I=Ia?ya.availHeight:a.innerHeight||c.clientHeight||b.body.clientHeight;d.rect=va(d.o);d.rect.visi={x:D(d.rect.width*Math.sqrt(Q)/2),y:D(d.rect.height*Math.sqrt(Q)/2),x2:D(d.rect.width*Math.sqrt(M)/2),y2:D(d.rect.height*Math.sqrt(M)/2)};y("rect")});var Za=0;r("unload",function(){if(Z&&!d.o){var a=L?L:w.body,b=L?"myel":"body",c=
"no wabbit ["+Za+"@"+(ca()-Ra)+" {"+(h.performance?Ra-Aa.performance.timing.navigationStart:0)+"}] ("+hb.join("|")+"): ",e=a.ownerDocument.body;if(e){e=va(e);var f=a.ownerDocument.documentElement;c+=b+"@{"+[e.left,e.right,e.top,e.bottom].join()+"} ("+f.clientWidth+"x"+f.clientHeight+")"}else c+="no body";if(X!=h){c+=", frm@";try{var v=K(h),l=a.ownerDocument.body;if(l){var k=va(l);f=v.ownerDocument.documentElement;c+="{"+[k.left,k.right,k.top,k.bottom].join()+"} ("+f.clientWidth+"x"+f.clientHeight+
")"}else c+="no body"}catch(uc){c+="cross-origin"}}ia(c)}});var e={},sb=0;(function(){var a=!1;try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),a=!0}catch(b){C.mimeTypes&&C.mimeTypes["application/x-shockwave-flash"]!=m&&C.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=!0)}return a})();var na={},tb=[],ub={},Vb=function(a){var b,c=[],d="";if("undefined"==typeof a[0])return null;for(var f=0;f<a.length;f++)if("undefined"!=typeof a[f]&&!1!==a[f]&&null!=a[f])if(b=a[f].match(/^t(?:agco|c)_(.*)$/)){var e=
a[f].split("=");var l=e[0];e.shift();d+="&"+l+"="+O(e.join("="));na[b[1]]=O(e.join("="))}else a[f].match(/(plat|plan|sup|adv)=/)?tb.push(a[f]):a[f].match(/_ap_[a-z]+=/)?(l=a[f].split("="),ub[l[0].slice(4,l[0].length)]=l[1]):c.push(a[f]);if(na.constructor===Object&&0===Object.keys(na).length)for(var k in p)if(b=k.match(/^t(?:agco|c)_(.*)$/))l=k,f=O(H(p[k])),d+="&"+l+"="+f,na[b[1]]=f;a||(da=c);return d},Ea=Vb(da),nc=function(){for(var a=w.getElementsByTagName("img"),b=0;b<a.length;b++){var c=a[b],d=
/^https?:\/\/[a-z]+\.adlooxtracking\.com\/ads\/transparent\.gif[#?](.*)/;if(c=c.src&&c.src.match(d)){a=c[1];b=a.split("&");for(c=0;c<b.length;c++){d=b[c].split("=");var f=d[0],e=f.match(/^t(?:agco|c)_(.*)$/);e?(d.shift(),na[e[1]]=O(d.join("="))):da.push(f)}return a}}return""};null!=Ea&&Ea.match(/tagco_pixel/)&&(Ea=nc(),Vb(Ea));var oc=function(a){var b=a.domain,c=1==a.version?"":a.version;delete a.domain;delete a.version;a.imp_id=Y;a="https://"+b+"/v"+c+"/?"+wa(a);Ha(a)};Ea&&r("visi",function(){var a=
Qa(Ea.substr(1));H(a,"tagco_domain");var b=a.tagco_domain;H(a,"tagco_version");var c=1==a.tagco_version?"":a.tagco_version;delete a.tagco_domain;delete a.tagco_version;var d={},e;for(e in a)H(a,e),d[e.substring(e.match(/^tc_/)?3:6)]=O(a[e]);d.imp_id=Y;d.visible=1;Ha("https://"+b+"/w"+c+"/?",d)});var pc=0<tb.length?"&"+tb.join("&"):"",Wb="",A=function(a){var b={};a=a.substring(a.indexOf("#")+1,a.length).split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");b[d[0]]=d[1]}return b}(L?L.src:"");
pb=A.uid||"";for(var vb="pbid cmp crid crsize tagid adv seller cpg".split(" "),La=0;La<vb.length;La++)"undefined"!==typeof A[vb[La]]&&(Ba["id"+String(La+1)]=A[vb[La]]);da=[A.pbid,A.cmp,A.crid,A.crsize,A.tagid];"undefined"!==typeof A.adv&&da.push(A.adv);"undefined"!==typeof A.seller&&da.push(A.seller);"undefined"!==typeof A.cpg&&da.push(A.cpg);"matiro_adnxs"==A.client&&(A.client="1000mercis_adnxs");Rb="cmp_"+A.client;Sb="ban_"+A.client;ba=A.client.replace("_adnxs","")||"adnxs";mb=D(A.height)||mb;lb=
D(A.width)||lb;Ob=A.aid||"";Wb=A.price||"";nb=12;var oa=function(){function a(a,c){var b=(a+"").lastIndexOf(c);return 0<=b?b:!1}try{return ta="1: parent.parent.location.href",Kb.parent.location.href}catch(b){try{return ta="2: parent.location.href",Kb.location.href}catch(c){if(a(c.message,"<"))return c.message.substring(a(c.message,"<")+1,a(c.message,">"));ta="3:  location.href";return aa.href}}}()||"",qc=function(){var a=[];if("undefined"==typeof aa.ancestorOrigins||!(aa.ancestorOrigins instanceof
DOMStringList))return a;for(var b=aa.ancestorOrigins.length;0<b--;)a.push(aa.ancestorOrigins.item(b));return a}(),rc=function(){var a={},b=C.userAgent.toLowerCase();a.O=0<b.indexOf("linux")?"Linux":0<b.indexOf("mac")?"Mac":0<b.indexOf("win")?"Windows":"inconnu";a.M=/Edge\/\d./i.test(C.userAgent)?"edge":0<b.indexOf("chrome")?"chrome":0<b.indexOf("firefox")?"firefox":0<b.indexOf("safari")?"safari":0<b.indexOf("opera")?"opera":0<b.indexOf("msie")||h.MSStream?"Internet Explorer":"inconnu";return a}(),
sc=oa;if(ib){oa=w.referrer;ta="6: top != window -> document.referrer "+aa.href;Ua&&(oa=aa.href,ta="7: top != window & friendly -> location.href "+w.referrer);"about:blank"==oa&&(oa=aa.href);try{qb=K(h).id+"@"+aa.href}catch(a){qb="frame without title"}}""==oa&&(ta="4: old_uri_courant",oa=sc);var wb=function(){function a(){var a,b={},c={Flash:"ShockwaveFlash.ShockwaveFlash.1",PDF:"AcroPDF.PDF",Silverlight:"AgControl.AgControl",QuickTime:"QuickTime.QuickTime"};if(h.ActiveXObject){var d=function(a){try{var b=
new ActiveXObject(a);try{return b.GetVariable("$version")}catch(J){try{return b.GetVersions()}catch(kc){try{for(a=9;0<a;a--)if(b.isVersionSupported(a+".0"))return a}catch(xc){}return!0}}}catch(J){return!1}},e;for(e in c)(a=d(c[e]))&&(b[e]=a);C.javaEnabled()&&(b.java="")}else{c.Java=m;d=C.plugins;for(var g in d)for(e in c)if((a=d[g].description)&&-1!=a.indexOf(e)){var B=d[g].version;b[e.toLowerCase()]=B?B:d[g].name+" "+a}}for(var r in b)a=/[0-9]+/.exec(b[r]),b[r]=a?a[0]:"";return b}var b=/^.* ([^ ]+)(.{2}) [^ ]+$/.exec(new Date);
b=b?b.slice(1).join(":"):"";var c="";try{c=JSON.stringify(a())}catch(f){}var d=function(a){if(!a.length)return b;for(var b=0,c=0;c<a.length;c++)b=(b<<5)-b+a.charCodeAt(c),b&=b;return b}(b+c)+function(){var a={monospace:m,"sans-serif":m,serif:m},b="cursive;monospace;serif;sans-serif;fantasy;default;Arial;Arial Black;Arial Narrow;Arial Rounded MT Bold;Bookman Old Style;Bradley Hand ITC;Century;Century Gothic;Comic Sans MS;Courier;Courier New;Georgia;Gentium;Impact;King;Lucida Console;Lalit;Modena;Monotype Corsiva;Papyrus;Tahoma;TeX;Times;Times New Roman;Trebuchet MS;Verdana;Verona".split(";"),
c=w.createElement("span");c.style.position="absolute";c.style.top=c.style.left="-1000px";c.style["font-size"]="72px";c.innerText="mmmmmmmmmmlli";w.body.appendChild(c);for(var d in a)c.style["font-family"]=d,a[d]=[c.offsetWidth,c.offsetHeight];var e=b.length;a:for(;0<e--;){for(d in a)if(c.style["font-family"]=b[e]+","+d,c.offsetWidth!=a[d][0]||c.offsetHeight!=a[d][1]){b[e]="t";continue a}b[e]="f"}w.body.removeChild(c);return b.join("")}();wb=function(){return d};return d},Ma=function(a){this.v=a;this.a=
null;this.a="function"==typeof h.__tcfapi?h.__tcfapi:this.j()};Ma.prototype.s=function(a){this.a("getTCData",2,a,[this.v])};Ma.prototype.l=function(a,b,c){c({msg:"CMP not found"},!1)};Ma.prototype.j=function(){var a=h;do{a=a.parent;var b=m;try{b=a.frames.__tcfapiLocator}catch(c){}if(b)return this.m(b.parent)}while(a!=h.top);return this.l};Ma.prototype.m=function(a){var b={};G(h,"message",function(a){var c=a.data.__tcfapiReturn&&a.data.__tcfapiReturn.callId;c in b&&(b[c](a.data.__tcfapiReturn.returnValue,
a.data.__tcfapiReturn.success),delete b[c])});return function(c,d,e,h){var f=Math.random().toString(16).substr(2);b[f]=e;a.postMessage({__tcfapiCall:{command:c,parameter:h,version:d,callId:f}},"*")}};var Na=function(){this.a=null;this.a="function"==typeof h.__uspapi?h.__uspapi:this.j()};Na.prototype.s=function(a){this.a("getUSPData",1,a)};Na.prototype.l=function(a,b,c){c({msg:"CMP not found"},!1)};Na.prototype.j=function(){var a=h;do{a=a.parent;var b=m;try{b=a.frames.__uspapiLocator}catch(c){}if(b)return this.m(b.parent)}while(a!=
h.top);return this.l};Na.prototype.m=function(a){var b={};G(h,"message",function(a){var c=a.data.__uspapiReturn&&a.data.__uspapiReturn.callId;c in b&&(b[c](a.data.__uspapiReturn.returnValue,a.data.__uspapiReturn.success),delete b[c])});return function(c,d,e,h){var f=Math.random().toString(16).substr(2);b[f]=e;a.postMessage({__uspapiCall:{command:c,parameter:h,version:d,callId:f}},"*")}};(function(){if(T){var a=5,b,c,e,f,v,l,k,p=-2,q=Infinity,Oa=!1,A,G=2,t=":"==T.substr(0,1)?"::"==T.substr(0,2)?"video":
"vpaid":"vast",J=!1,C={},z={impression:"AdImpression",creativeView:"AdStarted",start:"AdVideoStart",firstQuartile:"AdVideoFirstQuartile",midpoint:"AdVideoMidpoint",thirdQuartile:"AdVideoThirdQuartile",complete:"AdVideoComplete",click:"AdClickThru",acceptInvitation:"AdUserAcceptInvitation",collapse:"AdUserMinimize",close:"AdUserClose",pause:"AdPaused",resume:"AdPlaying",error:"AdError",skip:"AdSkipped",durationChange:"AdDurationChange"},I=function(a,b,c,e){switch(a){case "AdClickThru":J||(b={url:b,
id:c,playerHandles:e});break;case "AdImpression":if(Fa.state)return;Fa();break;case "AdPaused":case "AdVideoComplete":case "AdStopped":Ta=!1;break;case "AdPlaying":Ta=!0;break;case "AdDurationChange":p=d.f.duration}b=x(y,"VPAID."+a,b);"AdStopped"==a?ma(b,200):b()};r("VPAID.AdPaused",x(y,"sendvisi"));r("VPAID.AdPlaying",x(y,"sendvisi"));r("VPAID.AdStopped",la);var P=function(a,b){g&&g.stopAd.apply(g);y("VPAID.AdError",{code:a,message:b})},E=function(a){return a.textContent.trim()},M=function(a){var b=
w.createElement("iframe");b.src="javascript:false";b.style.display="none";b.onload=function(){var c=w.createElement("script");c.src=Pa(E(a));var d=a.getAttribute("type");d&&(c.type=d);b.contentWindow.document.getElementsByTagName("head")[0].appendChild(c)};Hb(b,L)},K=function(a){function e(){for(var a in F)d.f.removeEventListener(a,F[a]);d.o.removeEventListener("click",f);delete d.f.src}function f(){I("AdClickThru",{url:A,playerHandles:!0})}J=!0;var u,h,N,F={durationchange:function(){0<d.f.duration&&
d.f.duration!=p&&I("AdDurationChange")},canplay:function(){I("AdLoaded")},playing:function(){I("AdVideoStart");I("AdImpression")},play:function(){I("AdPlaying")},pause:function(){I("AdPaused")},timeupdate:function(){Oa||(Oa=q<d.f.currentTime)&&I("AdSkippableStateChange");2>G&&I("AdRemainingTimeChange");var a=d.f.currentTime/p;!N&&.75<=a&&(N=!0,I("AdVideoThirdQuartile"));!h&&.5<=a&&(h=!0,I("AdVideoMidpoint"));!u&&.25<=a&&(u=!0,I("AdVideoFirstQuartile"))},ended:function(){I("AdVideoComplete");g.stopAd()},
error:function(){P(405,d.f.error?d.f.error.message:"unable to load video")}};g={};g.subscribe=g.unsubscribe=W;g.startAd=function(){g.startAd=function(){return P(901,"startAd already called")};d.f.play();I("AdStarted")};g.stopAd=function(){g.startAd=function(){return P(901,"stopAd already called")};e();I("AdStopped")};g.pauseAd=function(){d.f.pause()};g.resumeAd=function(){d.f.play()};g.expandAd=g.collapseAd=W;g.skipAd=function(){Oa&&(e(),I("AdSkipped"),2>G&&I("AdStopped"))};g.getAdLinear=function(){return!0};
g.getAdWidth=function(){return b};g.getAdHeight=function(){return c};g.getAdExpanded=function(){return!1};g.getAdSkippableState=function(){return Oa};g.getAdRemainingTime=function(){return p-d.f.currentTime};g.getAdDuration=function(){return p};g.getAdCompanions=function(){return k};g.getAdIcons=function(){return!1};for(var n in F)d.f.addEventListener(n,F[n]);A&&d.o.addEventListener("click",f);d.f.src="string"==typeof a?a:E(a);d.f.preload="auto";d.f.load();return!0},N=function(a,e,k,h){for(var u=
[],F=0;F<a.length;F++){var n=a[F];if(!n.getAttribute("apiFramework")){var R=n.getAttribute("type"),l=n.getAttribute("codec");l&&(R+=';codecs="'+l+'"');if(d.f.canPlayType(R)){var g=n.getAttribute("width"),v=n.getAttribute("height");R="true"==(n.getAttribute("scalable")||"false").toLowerCase();l="true"==(n.getAttribute("maintainAspectRatio")||"true").toLowerCase();!(e||R||g==b&&v==c)||!k&&R&&1<g*v/(b*c)||(g=b/g/(c/v),!k&&R&&l&&(.95>=g||1.05<=g)||!h&&0<f&&(n.getAttribute("bitrate")>f||n.getAttribute("maxBitrate")>
f)||u.push(n))}}}u=u.sort(function(a,b){var c=a.getAttribute("bitrate")||a.getAttribute("maxBitrate"),d=b.getAttribute("bitrate")||b.getAttribute("maxBitrate");return h?c-d:d-c});n=u[0];for(F=1;F<u.length;F++)R=n.getAttribute("width"),l=n.getAttribute("height"),g=u[F].getAttribute("width"),v=u[F].getAttribute("height"),1-Math.abs(g*v/(b*c))<1-Math.abs(R*l/(b*c))&&(n=u[F]);return n?K(n):e&&k&&h?P(400,"no suitable media"):N(a,!0,!!e,!!k)},F=function(a){var d=w.createElement("iframe");d.src="javascript:false";
d.style.display="none";d.onload=function(){var u=w.createElement("script");u.src=Pa(a);u.onload=function(){var a=d.contentWindow.getVPAIDAd;if("function"!=typeof a)return P(901,"VPAID unit has no getVPAIDAd");g=a();for(var u in z)a=z[u],g.subscribe.apply(g,[x(I,a),a,this]),delete C[a];for(u in C)g.subscribe.apply(g,[x(I,u),u,this]);g.initAd.apply(g,[b,c,e,f,v,l])};d.contentWindow.document.body.appendChild(u)};L.parentNode.appendChild(d)},kb=function(b,c){var d=new XMLHttpRequest;d.open("GET",Pa(b));
d.withCredentials=!c;d.onload=function(){if(4==this.readyState){if(400<=this.status)return P(300,"failed to fetch VAST");var b=fc(this.response);if(b)a:if("VAST"!=b.documentElement.tagName)P(101,"not a VAST tag");else if(b=b.getElementsByTagName("Ad")[0]){var c=b.getElementsByTagName("Tracking");for(var d=[],e=c.length;0<e--;)d.push(c[e]);c=b.getElementsByTagName("Impression");for(e=c.length;0<e--;)c[e].setAttribute("event","impression"),d.push(c[e]);c=b.getElementsByTagName("Error");for(e=c.length;0<
e--;)c[e].setAttribute("event","error"),d.push(c[e]);c=b.getElementsByTagName("ClickTracking");for(e=c.length;0<e--;)c[e].setAttribute("event","click"),d.push(c[e]);for(e=d.length;0<e--;)if(c=E(d[e]),c.match(/^https?:/)){var u=d[e].getAttribute("event");(u=z[u])&&r("VPAID."+u,x(xa,c))}if(e=b.getElementsByTagName("VASTAdTagURI")[0])0>a--?P(302,"too many wrappers"):kb(E(e));else if(e=b.getElementsByTagName("Linear"),(d=e[0].getAttribute("skipoffset"))&&(q=Date.parse("1970-01-01 "+d+"Z")/1E3),d=e[0].getElementsByTagName("Duration"),
d.length&&(p=Date.parse("1970-01-01 "+E(d[0])+"Z")/1E3),d=e[0].getElementsByTagName("MediaFile"),d.length){c=b.getElementsByTagName("Survey");for(e=c.length;0<e--;)M(c[e]);c=b.getElementsByTagName("JavaScriptResource");for(e=c.length;0<e--;)M(c[e]);e=b.getElementsByTagName("ClickThrough");e.length&&(c=E(e[0]),c.match(/^https?:/)&&(A=c));for(e=0;e<d.length;e++)if(c=d[e],"VPAID"==c.getAttribute("apiFramework")&&"application/javascript"==c.getAttribute("type")){v=b.getElementsByTagName("AdParameters");
v={AdParameters:v.length?E(v[0]):""};k=b.getElementsByTagName("AdCompanions");k=k.length?E(k[0]):"";F(E(c));break a}N(d)}else P(403,"no media files")}else P(400,"no Ad");else return P(100,"unable to parse XML")}};d.onerror=function(){c?P(303,"unable to download VAST"):kb(b,!0)};d.ontimeout=x(P,301,"timeout to download VAST");d.timeout=5E3;d.send(null)},n={handshakeVersion:function(a){a=D(a);2>a&&(G=a);return G+".0"},initAd:function(a,n,k,h,g,N){if(d.o)return P(901,"initAd already called");b=a;c=n;
e=k;f=h;(g&&g.AdParameters||"").match(/(?:^|&)vpaid=adloox(?:$|&)/)?(a=Qa(g.AdParameters),v={AdParameters:H(a.adparameters)}):"vpaid"==t&&(v=g);l=N;r("adunit",function(){switch(t){case "vpaid":return F(T.substr(1));case "video":return K(T.substr(2));case "vast":return kb(T)}});r("fw",function(a){a.state&&(I("AdError",{code:408,message:"adloox.com brand safety"}),I("AdStopped"))});Ub(N.slot);d.f=N.videoSlot},subscribe:function(a,b,c){switch(b){case "AdError":var d=function(b){a.apply(c,[b.message])};
break;case "AdClickThru":d=function(b){a.apply(c,[b.url,b.id,b.playerHandles])};break;default:d=a.bind(c)}r("VPAID."+b,d);C[b]=1},unsubscribe:function(a,b){eb("VPAID."+b,a)},getAdCompanions:function(){return"vpaid"==t?k:g.getAdCompanions.apply(g)},has:function(a,b){return g?!!g[b]:!0},get:function(a,b){return a&&a[b]?a[b]:x(function(){for(var a=[],c=arguments.length;0<c--;)a.unshift(arguments[c]);if(g&&g[b])return g[b].apply(g,a)})},set:function(a,b,c){return function(){g&&(g[b]=c);return!!g}}};if(h.getVPAIDAd)return P(901,
"VPAID already in window");h.getVPAIDAd=x(function(){n.getAdloox=L.getAdloox;if(h.Proxy)return new h.Proxy(n,n);for(var a="resize start stop pause resume expand collapse skip".split(" "),b=a.length;0<b--;){var c=a[b]+"Ad";n[c]=n.get(m,c)}a="Linear Width Height Expanded SkippableState RemainingTime Duration Volume Icons".split(" ");for(b=a.length;0<b--;)c="getAd"+a[b],n[c]=n.get(m,c);a=["Volume"];for(b=a.length;0<b--;)c="setAd"+a[b],n[c]=n.set(m,c);return n})}})();var ka=null,xb="visible",$a=["","moz",
"ms","webkit"];for(fa=0;fa<$a.length;fa++){var yb=$a[fa]+(fa?"H":"h")+"idden";if(w[yb]!==m){var zb=$a[fa]+(fa?"V":"v")+"isibilityState";ka=w[yb];xb=w[zb];G(w,$a[fa]+"visibilitychange",function(){ka=w[yb];xb=w[zb];y("pagevisi")});break}}var Ga,Ab,Xb=function(a,b){b===m&&(b=ka);Ga+=b?0:a-Ab;Ab=a};r("booted",function(){Ga=0;Ab=ca();r("pagevisi",function(){Xb(ca(),!ka)})});var V={};r("adunit",function(){function a(){var c=ca();if(!(1E3>c-a.H)){300<c-b.K&&b();e.p_d=(ca()-Ra)/1E3;e.p_d_v=Ga/1E3;e.browser=
rc.M;e.hash=wb();e.hash_adnxs=pb;e.visi_debug="booting: "+J+" ["+[A.G,l.a].join()+"]";d.rect&&(e.size=d.rect.width+"x"+d.rect.height);if(!J){var f=b.v?2:0,k=b.w?2:0;if(Z){var n=f?isNaN(b.exp)||0==b.exp?0:b.exp/1E3:0,h=e.p_d,g=k?isNaN(b.a)||0==b.a?0:b.a/1E3:0,v=b.s?2:0,m=d.rect?d.rect.width+"x"+d.rect.height:0;try{Da(n,h,f,g,v,m)}catch(yc){}Da=W}n=L||b.summary;h=[];for(var t in n)g=n[t],h.push(t+"."+("number"==typeof g?1+~~(.5>g):null!==g?1+~~g:0));e.visi_debug=h.join("_");e.visible=f;e.a_d=b.exp/
1E3;e.wasatf=b.s?2:0;U?(e.visible2=~~(2E3<=Ga)?2:0,e.a_d2=Ga/1E3,e.wasatf2=2):0<M&&(e.visible2=k,e.a_d2=b.a/1E3,e.wasatf2=b.D?2:0)}e.seq=++sb;cb(e);a.H=c}}function b(){var a=ca(),d=a-(b.K||a);b.K=a;Z||h.setTimeout(b,100);0>J&&(ia("booting < 0, this should not happen!"),J=0);if(!J&&(v(),Xb(a),L=b.L,b.L={page:ka,homepage:t.hidden,focus:x.hidden,classic:p.ratio,element:z.hidden[0],safeframe:m.ratio,mraide:k.j,mraidr:k.ratio,mraidh:k.hidden,intersection:q.hidden,animation:l.hidden[0]},C&&Ta)){var e=[],
n=[];e.push(ka);n.push(ka);e.push(t.hidden);n.push(t.hidden);e.push(x.hidden);n.push(x.hidden);null!==p.ratio&&(e.push(p.ratio<Q),n.push(p.ratio<M));z();c(e,z.hidden);c(n,z.g);za&&(m(),null!==m.ratio&&(e.push(m.ratio<Q),n.push(m.ratio<M)));null!==k.j&&(e.push(k.j<Q),n.push(k.j<M));null!==k.ratio&&(e.push(k.ratio<Q),n.push(k.ratio<M));null!==k.hidden&&(e.push(k.hidden),n.push(k.hidden));null!==q.hidden&&e.push(q.hidden);null!==q.g&&n.push(q.g);c(e,l.hidden);c(n,l.g);for(var u=a=!1,r=0;r<e.length;r++)if(e[r]){a=
!0;break}for(r=0;r<n.length;r++)if(n[r]){u=!0;break}b.hidden=a;b.g=u;null===b.s&&(b.s=U?!0:!a);null===b.D&&(b.D=U?!0:!u);a?b.l=0:(b.exp+=d,b.l+=d,b.l>b.max&&(b.max=b.l));u?b.m=0:(b.a+=d,b.m+=d,b.m>b.F&&(b.F=b.m));e=b.v;b.v=b.max/1E3>=ja?2:0;e!=b.v&&f();0<M&&(e=b.w,b.w=b.F/1E3>=ra?2:0,e!=b.w&&g());h.adloox_getVisi=!a&&!u;V.C={atf:[b.s,b.D],dur:ca()-Ra,dat:Ga,exp:[b.exp,b.a],max:[b.max,b.F],run:[b.l,b.m],vwb:[b.v,b.w],hid:[a,u]};V.J={page:ka,homepage:t.hidden,focus:x.hidden,classic:p.ratio,element:[z.hidden,
z.g],safeframe:m.ratio,mraide:k.j,mraidr:k.ratio,mraidh:k.hidden,intersection:[q.hidden,q.g],animation:[l.hidden,l.g]};y.a.viewability&&y.a.viewability.length&&y("viewability",{delta:d,metrics:V.C,sensors:V.J})}}function c(a,b){null!==b[0]&&null!==b[1]&&null!==b[2]&&a.push(b[1]&&(b[0]||b[2]))}function g(){g=W;y("visi_custom")}function f(){f=W;y("visi")}function v(){v=W;y("booted")}function l(a){var b=a.c?l.g:l.hidden;l.a&&null===b[a.i]&&(l.a--,l.a||(J--,C=!0));b[a.i]=a.h;a.c||1!=a.i||(l.g[1]=a.h)}
function k(){var a=!1,b=!1;switch(D(E.getVersion())){case 3:G(E,"exposureChange",function(a){k.j=a/100});case 2:r("rect",function(){var a="function"==typeof E.getCurrentPosition&&E.getCurrentPosition();"object"!=typeof a&&(a={x:0,y:0});var b="function"==typeof E.getScreenSize&&E.getScreenSize();b||(b=d.B.documentElement,b={width:b.clientWidth,height:b.clientHeight});k.ratio=Math.max(Math.min(b.width-a.y,0),d.rect.width)*Math.max(Math.min(b.height-a.x,0),d.rect.height)/(d.rect.width*d.rect.height)});
default:var c=function(c){a="loading"!=c&&"hidden"!=c;k.hidden=!a&&!b};G(E,"stateChange",c);c(E.getState());3>zb&&(c=function(c){b=c;k.hidden=!a&&!b},G(E,"viewableChange",c),c(E.isViewable()))}}function m(){try{var a=D(za.ext.inViewPercentage());isNaN(a)||(m.ratio=a/100)}catch(F){}try{x.hidden=!za.ext.winHasFocus()}catch(F){}}function p(){J--;C=!0;p=function(){var a=Math.min(d.N-d.rect.left,d.rect.width);a+=Math.min(d.rect.left,0);a=Math.max(a,0);var b=Math.min(d.I-d.rect.top,d.rect.height);b+=Math.min(d.rect.top,
0);b=Math.max(b,0);p.ratio=a*b/(d.rect.width*d.rect.height)};p()}function q(a){q.s&&(h.clearTimeout(q.s),delete q.s,J--,C=!0);q.hidden=a[0].intersectionRatio<Q;q.g=a[0].intersectionRatio<M}function x(){try{x.hidden=!X.document.hasFocus(),G(X,"focus",function(){x.hidden=!1}),G(X,"blur",function(){x.hidden=!0})}catch(N){}}function A(){function a(a){var b="";switch(a.tagName){case "IMG":a.src&&(b=a.src);break;default:var c="object"==typeof a.style&&a.style["background-image"];c&&(c=c.match(/^url\("?([^")]+)"?\)$/))&&
(b=c[1])}if(b.match(/^https?:/)&&"none"!=a.style.display&&"none"!=a.style.visibility){var d=function(){--A.G||J--};c=function(){d()};var e="IMG"==a.tagName?a:new Image;G(e,"load",c);G(e,"error",c);"IMG"!=a.tagName&&(e.src=b);e.complete||4===e.readyState||0<e.naturalWidth?d=W:A.G++||J++}}A.G=0;var b=Jb(d.o.getElementsByTagName("*"));b.push(d.o);for(var c=b.length;0<c--;)a(b[c])}function t(){J--;C=!0;t=function(){t.hidden=Eb(d.A).y>d.I};t()}var J=0,C=!1;t.hidden=null;U&&(J++,r("rect",function(){t()}));
U||T||A();x.hidden=null;Ia||x();q.hidden=null;q.g=null;if(!U)try{q.l=new IntersectionObserver(q,{threshold:[Q,M]}),q.l.observe(d.o),J++,q.s=Ja(function(){q([{intersectionRatio:0}])},100)}catch(N){}p.ratio=null;U||q.l||(J++,r("rect",function(){p()}));var z=U||!Sa?W:function(){var a=d.B,b=[d.rect.left+D(d.rect.width/2),d.rect.top+D(d.rect.height/2)],c=!a.elementFromPoint(b[0],b[1]);z.hidden=[!a.elementFromPoint(b[0]-d.rect.visi.x,b[1]-d.rect.visi.y),c,!a.elementFromPoint(b[0]+d.rect.visi.x,b[1]+d.rect.visi.y)];
z.g=[!a.elementFromPoint(b[0]-d.rect.visi.x2,b[1]-d.rect.visi.y2),c,!a.elementFromPoint(b[0]+d.rect.visi.x2,b[1]+d.rect.visi.y2)]};z.hidden=[null,null,null];z.g=[null,null,null];if(!U&&Sa){J++;var I=function(){I=W;J--;C=!0};r("rect",function(){I()})}m.ratio=null;r("safeframe",m);k.j=null;k.ratio=null;k.hidden=null;r("mraid",k);l.v=Math.min(-1E3,(D(Gb(d.o)["z-index"])||0)-1E3);l.w=function(){function a(a,b){function e(){if(1==a)f.style.top=f.style.left="50%";else{var c=d.rect.visi;c=50-D(100*(b?c.x2:
c.x)/d.rect.width)+"%";a?f.style.bottom=f.style.right=c:f.style.top=f.style.left=c}}var f=c.createElement("iframe");r("rect",e);d.rect&&e();f.style.position="absolute";f.style.width=f.style.height="8px";f.style["pointer-events"]="none";f.style["z-index"]=l.v+1;f.style["border-style"]="none";f.style["background-color"]="transparent";var k=w.createElement("html"),g=w.createElement("head"),h=w.createElement("script");h.innerText="var l, w, h = null, f = function(n){ clearTimeout(w); var hh = n ? n - l > 90 : true; if (h != hh) { h = hh; parent.postMessage({ c: "+
b+", i: "+a+', h: h }, "*") }; if (n) setTimeout(q, 100) }, q = function(){ l = performance.now(); w = setTimeout(f, 100); requestAnimationFrame(f) }; onload = q';g.appendChild(h);k.appendChild(g);f.sandbox="allow-scripts";f.srcdoc=k.outerHTML;f.onload=function(){l.m.push(f.contentWindow)};c.body.appendChild(f)}l.m=[];var b=d.u.contentWindow,c=b.document;b.onmessage=function(a){for(var b=l.m.length;0<b--;)l.m[b]===a.source&&l(a.data)};for(b=0;3>b;b++)a(b,!1),0<M&&1!=b&&a(b,!0)};l.hidden=[null,null,
null];l.g=[null,null,null];if(!(U||jc||"function"!=typeof h.requestAnimationFrame||Sa||q.l)){J++;d.u=d.B.createElement("iframe");var K=function(){ma(function(){try{d.B.body.removeChild(d.u)}catch(N){}delete d.u},0)};G(d.u,"load",function(){try{d.u.contentWindow.document&&(r("rect",function(){var a=d.rect,b=Eb(d.A),c=d.u.style;c.top=a.top+b.y+"px";c.left=a.left+b.x+"px";c.width=a.width+"px";c.height=a.height+"px"}),l.a=3,0<M&&(l.a+=2),l.w())}catch(N){K(),J--}});d.u.setAttribute("data-adloox-type",
"proxy");d.u.setAttribute("data-adloox-sid",Y);Gb(d.o);var H=d.u.style;H.position="absolute";H["pointer-events"]="none";H["z-index"]=l.v;H["border-style"]="none";H["background-color"]="transparent";d.B.body.appendChild(d.u);r("unload",K)}var L;b.hidden=null;b.g=null;b.s=null;b.D=null;b.exp=0;b.a=0;b.max=0;b.F=0;b.l=0;b.m=0;b.v=0;b.w=0;a.H=0;r("booted",function(){r("sendvisi",a)});r("unload",function(){eb("sendvisi",a);S||a()});if((Nb||ka)&&!T){r("visi"+(M>Q?"_custom":""),function(){ma(a,Math.floor(2E3*
Math.random()))});var O=1;(function F(){Z||(Ja(function(){a();F()},Math.floor(1E3*(O+(1==O?2*Math.random():0)))),O=Math.min(64,2*O))})()}b()});r("impression",function(){G(h,"unload",x(la));G(h,"beforeunload",x(la));G(h,"pagehide",x(la))});"zebestof"==ba&&r("impression",function(){Va.push(function(){return"https://adloox.zebestof.com/visibility?v=[ADL_VW]&f=[ADL_FW]&"+wa({b:Ba.id10})})});var tc=function(){return{config:{visite_id:Y,cname:ba,platform:nb,version:"a661c72",date_regen:"2021-04-21 08:21:02",
fwtype:ea,creatype:Ka,targetelt:pa,iframe:ib?Ua?"same-origin":"cross-origin":"none",features:{safeframe:!!za,mraid:!!E,vast:!!T},viewability:{iab:{time:ja,area:Q},custom:{time:ra,area:M}}},metrics:x(function(){var a=V&&V.C;return a?{hidden:a.hid[0],hidden_custom:a.hid[1],viewable:!!a.vwb[0],viewable_custom:!!a.vwb[1],atf:!!a.atf[0],atf_custom:!!a.atf[1],duration:a.dur,duration_activetab:a.dat,exposure:a.exp[0],exposure_custom:a.exp[1],exposure_max:a.max[0],exposure_max_custom:a.max[1],exposure_run:a.run[0],
exposure_run_custom:a.run[1]}:"still booting"}),sensors:x(function(){var a=V&&V.J;return a?a:"still booting"}),impression:x(function(){return Fa.state}),adunit:x(function(){return{el:d.o,proxy:d.u,rect:d.rect}}),subscribe:x(function(a,b){r(a,b)}),unsubscribe:x(function(a,b){eb(a,b)})}};L&&(L.getAdloox=x(function(){return new tc}));r("adunit",function(){var a=x(y,"sendvisi");r("pagevisi",a);E&&(G(E,"viewableChange",a),G(E,"stateChange",a))});var Yb=m,Zb=m;r("impression",function(){function a(){function a(){cb(e);
S=!1;y("fw",{state:S})}if(Xa){var b=function(a){if("boolean"!=typeof S){S=!1;a="string"==typeof a?a:"";"%%BLOCK%%"==a.trim()&&(S=!0,la());a=a.split("\n").filter(function(a){return/^\p{L}[\p{L}\p{Z}+]*$/u.test(a.trim())});if(!S&&a.length){var b=function t(a){for(var b=[a],c=a.frames.length;0<c--;)b.push.apply(b,[].concat(dc(t(a.frames[c]))));return b}(h.top).reduce(function(a,b){try{a.push.apply(a,[].concat(dc(b.document.querySelectorAll("title,h1,h2,h3,h4,h5,h6,p"))))}catch(kc){}return a},[]).map(function(a){return a.innerText}).join("\n");
try{var c=(new RegExp(a.map(function(a){return a.split("+").map(function(a){return"(?=.*\\b("+a.trim()+")\\b)"}).join("")}).join("|"),"ui")).exec(b);if(S=!!c)e.seq=++sb,e.ads_forceblock=1,e.alerte_desc="keyword content:"+c.splice(1).filter(function(a){return a}).join("+"),cb(e)}catch(t){}}y("fw",{state:S})}},c=function(){var c=String.fromCharCode(97+26*Math.random())+Math.random().toString(16).substr(2);Object.defineProperty(h,c,{value:function(a){b(a)}});e.jsonp=c;ec(e,function(b){"load"!=b&&a()});
delete e.jsonp};try{var d=new XMLHttpRequest;d.open("GET","https://data00.adlooxtracking.com/ads/ic5.php?"+wa(e));d.onload=function(){if(4==d.readyState){if(400<=d.status)return c();b(d.responseText)}};d.onerror=c;d.ontimeout=c;d.timeout=5E3;d.send(null)}catch(vc){c()}}else a();na.domain&&na.version&&oc(na)}function b(a){e["popup_"+a]="object"==typeof h[a]?h[a].visible:-1}Ta=!0;var c=0;try{c=(new Date).getTimezoneOffset()}catch(v){}var d=h.ctitle_atlas?h.ctitle_atlas:"";e.adloox_io=1;e.seq=sb;e.campagne=
Rb;e.banniere=Sb;e.plat=nb;e.adloox_transaction_id=Ob;e.bp=Wb;e.visite_id=Y;e.client=ba;e.ctitle=d;e.os="";e.navigateur="";e.appname=C.appName?C.appName:"unknown";e.timezone=c;e.fai=qb;e.data=wb();e.js="tfav_script1_appnexus.js";e.commitid="a661c72";e.fw=ea;e.version=Ca;e.iframe=ib?Ua?3:1:0;e.hadnxs=pb;e.ua=C.userAgent;e.url_referrer=oa;e.resolution=lc;e.nb_cpu=Tb;e.nav_lang=mc;e.date_regen="2021-04-21 08:21:02";e.debug=ta;e.ao=qc[0]||"";e.fake=""+~~Lb+~~ic+~~gc+~~Sa+~~hc+~~(0==ya.height&&0==ya.width||
0==h.devicePixelRatio);e.popup_history=Math.max(history.length,9);e.popup_visible="visible"==xb;e.type_crea=Ka;e.tagid=Pb;e.tc=Yb;e.usp=Zb;b("menubar");b("locationbar");b("personalbar");b("scrollbars");b("statusbar");b("toolbar");for(var f in Ba)e[f]=e[f]||Ba[f];c=Qa(pc.substr(1));for(f in c)H(c,f),e[f]=e[f]||c[f];ub.sizmek&&(e.sizmek=ub.sizmek);"function"==typeof C.a?C.a().then(function(b){for(f in b)"string"==typeof b[f]&&b[f].length&&(e["ch_ua_"+f]=b[f]);a()}):a()});var Fa=function(){Fa.state=
!0;y("impression")},$b=function(){function a(b,c){a=W;Zb="boolean"==typeof c?b.uspString:"";--d||ma(Fa,0)}function b(a,c){b=W;Yb="boolean"==typeof c?a.tcString:"";--d||ma(Fa,0)}r("impression",function v(){if(!Z){Za++;var a=null;if(U)try{a=X.document.body}catch(k){a=m}else a=qa(L);a?Ub(a):null===a?ma(v,Math.min(5E3,Za*Za*200)):la()}});if(!U){if(!Ua){var c=Ib(aa);za=Fb("$sf",function(a){return c.hostname.match(/(?:^|\.)adnxs\.com$/)?!1:"object"==typeof a&&"object"==typeof a.ext})}za&&(hb.push("SafeFrame"),
y("safeframe"));if(E=Fb("mraid",function(a){return"object"==typeof a&&"function"==typeof a.getVersion&&D(a.getVersion())&&"function"==typeof a.getPlacementType&&"function"==typeof a.getState}))hb.push("MRAID"),y("mraid")}var d=2;(new Ma(93)).s(b);(new Na).s(a);Ja(function(){b();a()},2E3)},ac=function(){var a=w.createElement("link");a.rel="preconnect";a.href="https://data00.adlooxtracking.com";w.getElementsByTagName("head")[0].appendChild(a)};T?ac():ob||"loading"!==w.readyState?$b():(w.addEventListener("DOMContentLoaded",
$b),ac())}catch(a){ia(a.stack||a.message)}}}).call(this);
